import os
import shutil
import subprocess
from app.helpers.pdf_reader import process_pdf


def convert_word_to_pdf(docx_path: str, output_dir: str) -> str:
    libreoffice_cmd = (
        shutil.which("soffice")
        or shutil.which("libreoffice")
    )

    if not libreoffice_cmd:
        raise Exception(
            "LibreOffice is not installed."
        )

    try:
        subprocess.run(
            [
                libreoffice_cmd,
                "--headless",
                "--convert-to", "pdf",
                "--outdir", output_dir,
                docx_path,
            ],
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        pdf_name = (
            os.path.splitext(os.path.basename(docx_path))[0]
            + ".pdf"
        )

        pdf_path = os.path.join(output_dir, pdf_name)

        if not os.path.exists(pdf_path):
            raise Exception(
                "PDF not generated by LibreOffice."
            )

        return pdf_path

    except subprocess.CalledProcessError as e:
        raise Exception(
            f"LibreOffice conversion failed: "
            f"{e.stderr.decode(errors='ignore')}"
        )


def process_word(file_path: str):
    """Converts Word to PDF to preserve page numbers, then processes as PDF."""
    output_dir = os.path.dirname(file_path)

    pdf_path = convert_word_to_pdf(
        file_path,
        output_dir,
    )

    try:
        return process_pdf(pdf_path)
    finally:
        if os.path.exists(pdf_path):
            os.remove(pdf_path)
